modLoader="javafml"
loaderVersion="${loader_range}"
issueTrackerURL="https://github.com/EraofMagica/EoMantle/issues"
logoFile="EoMantle.png"
license="MIT"

[[mods]]
    modId="eomantle"
    version="${version}"
    displayName="EoMantle"
    authors="Slime Knights, To_Craft"
    description='''
Shared code for Slime Knights mods and others.
    '''
    displayURL="https://github.com/EraofMagica/EoMantle"

[[dependencies.eomantle]]
    modId="forge"
    mandatory=true
    versionRange="${forge_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.eomantle]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_range}"
    ordering="NONE"
    side="BOTH"
